# Generated by Django 4.0.5 on 2022-06-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('number_of_sessions', models.IntegerField()),
                ('has_assignment', models.BooleanField(default=False)),
                ('number_of_assignment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('has_assignment', models.BooleanField(default=False)),
                ('assignment_deadline', models.DateTimeField(null=True)),
                ('assignment_title', models.CharField(max_length=120)),
                ('assignment_description', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
